{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    {{- if $svc.metrics }}
    metrics: "true"
    {{- end }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
{{- end }}